### ISSUE TITLE
Question: InitializeScheduler dangerous

### ISSUE THREAD

**Issue by Swimburger** [Sitecore/configs#2]
Hi, would removing `InitializeScheduler` prevent Sitecore from running its agents?
I'm evaluating how safe it is to remove this part.
```
<processor type="Sitecore.Pipelines.Loader.InitializeScheduler, Sitecore.Kernel">
          <patch:delete />
</processor>
```

**Comment by alexshyba** [comment]
Hello,

Yes, but during website development I rarely need those. Most of the patches in this file are extremely experimental and are not recommended to be used on anything other than dev boxes.
If you do any work relying on scheduling, please remove this from your config.

-alex
